### ISSUE TITLE
Scipion is not awere of the status of submitted jobs

### ISSUE THREAD

**Issue by JuhaHuiskonen** [I2PC/scipion#2080] opened 2020-06-01 12:57 UTC
Sometimes submission of the job to a scheduling system fails (for example when the user asks for more memory than allowed in a particular queue).   Scipion shows this job with status "Launched".  It would be nice if Scipion kept checking if the job is actually in the queue or not (if it got a job ID or not).  If not, it should be marked as "Failed"

**Comment by pconesa** [comment] 2020-06-01 13:23
Thanks, @JuhaHuiskonen .... there is a CHECK_COMMAND (extracted from here: https://github.com/I2PC/scipion/blob/master/pyworkflow/templates/hosts.template)

CHECK_COMMAND = qstat %_(JOB_ID)s

Clearly this one needs the JOB_ID. 

So I guess the issue is before as you say. I'm moving this issue to Scipion3 repo. Will investigate this there.

**Closed by pconesa** 2020-06-01 13:23 UTC
