### ISSUE TITLE
Optical flow does not show parallel section

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#881] opened 2017-03-03 22:04 UTC

**Comment by pconesa** [comment] 2017-03-16 14:32
What's the status of this?

**Comment by cossorzano** [comment] 2017-03-16 14:56
I saw Josue working on this and the issue under review. However, I do 
not know in which branch it is and in release-1.1-fixes it is not fixed.

**Comment by pconesa** [comment] 2017-03-16 15:07
Ah! Now I remember. Laura reviewed all the STEPS_PARALELL protcolols. This should be fixed. I'll check with @ldelcano . I can confirm the bug is still present in release-1.1-fixes.

**Comment by pconesa** [comment] 2017-03-16 15:12
I close it since #885 includes this case.

**Closed** 2017-03-16 15:13 UTC
Labels: bug, gui, to-review
