### ISSUE TITLE
error: unable to open database file

### ISSUE THREAD

**Issue by brossa** [I2PC/scipion#792] opened 2017-02-01 10:34 UTC
Hi,
when working on a cluster with Scipion v1.0.1 I get the following error in the terminal:

```
[Errno 24] Too many open files
Error trying to update protocol: (jobId=278277)
 ERROR: Error creating SqliteMapper, dbName: /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
 error: unable to open database file, tries=0
[Errno 24] Too many open files
Error trying to update protocol: (jobId=278277)
 ERROR: Error creating SqliteMapper, dbName: /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
 error: unable to open database file, tries=1
[Errno 24] Too many open files
Error trying to update protocol: (jobId=278277)
 ERROR: Error creating SqliteMapper, dbName: /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
 error: unable to open database file, tries=2
[Errno 24] Too many open files
Error trying to update protocol: (jobId=278277)
 ERROR: Error creating SqliteMapper, dbName: /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
 error: unable to open database file, tries=3
Traceback (most recent call last):
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/project.py", line 381, in _updateProtocol
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/protocol/protocol.py", line 1601, in getProtocolFromDb
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/project.py", line 189, in load
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/project.py", line 216, in _loadDb
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/project.py", line 167, in createMapper
  File "/naslx/projects/pr23ja/gu62vos2/Programs/scipion/pyworkflow/mapper/sqlite.py", line 43, in __init__
Exception: Error creating SqliteMapper, dbName: /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
 error: unable to open database file
```
How can I fix this issue? Thanks in advance.

**Comment by pconesa** [comment] 2017-02-01 10:51
Dear brossa,

Seems there's something wrong with:

/naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db

Could you please, send it to me, or attach it to the issue?


||

**Comment by brossa** [comment] 2017-02-01 11:39
[file.zip](https://github.com/I2PC/scipion/files/744683/file.zip)

**Comment by pconesa** [comment] 2017-02-01 13:59
Thank you brossa.

I've downloaded it and openes it. It seems ok. I was expecting to find it corrupted or something like that, but seems to be ok.

Please, let me know if the following does sound to technical:

Could you please run in a terminal window:
`scipion run sqlite3 /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db`

You should get something like:

`SQLite version 3.6.23
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> 
`

And then 

`Select * from Objects;`


Are you getting any error message?


To quit just type:
`.quit`

**Comment by brossa** [comment] 2017-02-01 15:02
Okay...

When I run:
`scipion run sqlite3 /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db:`
I get the following output.
```
>>>>> "sqlite3" "/naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db"
sqlite3: error while loading shared libraries: libreadline.so.6: cannot open shared object file: No such file or directory
```
I think I am missing some sqlite libraries due to the fact that I need to unload/load some modules in order to get scipion running. 

So I tried without the "scipion run" part:
`sqlite3 /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db`
and the output is as follows:
```
SQLite version 3.7.6.3
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> Select * from Objects;
Error: unable to open database "/naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db": unable to open database file
```
I'm still a bit confused about the `[Errno 24] Too many open files` in the original error message. Could it be possible that my project just got too big?

**Comment by pconesa** [comment] 2017-02-01 15:29
Thanks, 
Well, I can open the db you've attached, but you can't....I wonder if there is any process/es blocking the database.

I guess this will check if the database file is opened. Run it with Scipion closed and no sqlite connected to it:

`lsof /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/013407_ProtRelionRefine3D/logs/run.db
`
Does it help?

**Comment by brossa** [comment] 2017-02-01 15:50
Sorry I deleted the file. But another run of the same protocol has the same issue:

sqlite3 /naslx/projects/pr23ja/gu62vos2/ScipionUserData/projects/SIP/Runs/012142_ProtRelionRefine3D/logs/run.db

Output:
[errorlog.txt](https://github.com/I2PC/scipion/files/745345/errorlog.txt)

**Comment by brossa** [comment] 2017-02-02 11:42
update:
issue only occurs when I run multiple protocols shortly after each other (e.g. 6x relion 3D refine at once) but when I wait for a few minutes before starting the next protocol everything is fine. looks like a weird bug to me.

**Comment by pconesa** [comment] 2017-02-03 10:36
umm, that may explain the issue. 6 process trying to access same db at 
some point.

Thanks for the feedback, for now all we can do is suggest you to wait 
(as you are doing). Quite likely the problem resides a the beginning of 
each process where there might be some concurrent access to the same 
project.db.

I'll leave the issue open for now, or may be later we will create 
another one summarizing this issue and close this one.

Thanks brossa,

Pablo.

**Comment by delarosatrevin** [comment] 2017-02-03 10:40
@brossa, thanks for the feedback. Can you comment about the filesystem where Scipion is installed there? (NFS, local, etc)

**Comment by brossa** [comment] 2017-02-03 10:59
scipion is installed on a NFS. 

and to make things worse: this issue does not only occur when I launch multiple protocols. I just continued a relion 3d refine run and got the same error (just one protocol this time)... the bad thing about this is, that the unfinished runs from yesterday are also affected. these runs are marked as "failed" in scipion, but they are still running and producing results as expected. I don't think that I will be able to continue with my work from this point because the results won't get written into the database due to the error. The data itself however is there.

**Comment by delarosatrevin** [comment] 2017-02-03 11:06
I was affraid about the NFS filesystem because in this one file operations take longer to be finished. (like opening or closing files). So, that could be the cause of the database being locked between protocols. We need to check about this issue.

I think that you can continue working with this project even if the protocols are marked as failed. The relion processes will keep running and producing results. The only difference is that you will need to check when they are done and you need to generate the output particles (or classes) to be used in the following steps. All the output files are not inserted in the database, only the required metadata. As I said, you can generate it from intermediate results (iterations) or from the final one when doing the "Analyze Results"

**Comment by delarosatrevin** [comment] 2017-02-03 11:11
Just a more technical comment, but related to this issues and to keep the remainder. I think we should check other alternatives for the Sqlite/Python library. The current one complains with the standard Python DB API, but lacks some properties provided natively by Sqlite. For example, it always opens the .sqlite file with writing permissions, it is not possible to do it in Read-Only mode. I'm not sure if RO could help for the case of files in a NFS filesystem.

**Comment by ic1062** [comment] 2018-01-29 20:36
Hello, I'm having the problem described in the original post with v1.1. Specifically, I can create a new project on a local filesystem but not on a remote (sshfs mounted) filesystem. I will appreciate any help resolving this since all of the workstation storage is on a server. 
Mike

Scipion v1.1 (2017-06-14) Balbino

#### creating project on local file system ####
>>>>> python  /ws/local/progs/scipion/pyworkflow/apps/pw_manager.py 
Creating project at:  /ws/home/krios/test/scipion-local-fs/project.sqlite
PROJECT: Warning, protocol view 'None' not found.
         Using 'Protocols SPA' instead.

### attempting to create project on remote file system ####
Creating project at:  /data2/Purdy/scipion-test/scipion-sshfs/project.sqlite
Exception in Tkinter callback
Traceback (most recent call last):
  File "/ws/local/progs/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/ws/local/progs/scipion/pyworkflow/gui/project/viewprojects.py", line 281, in _select
    self.parent.createNewProject(projName, projLocation)
  File "/ws/local/progs/scipion/pyworkflow/gui/project/viewprojects.py", line 151, in createNewProject
    self.manager.createProject(projName, location=projLocation)
  File "/ws/local/progs/scipion/pyworkflow/manager.py", line 96, in createProject
    protocolsConf=protocolsConf)
  File "/ws/local/progs/scipion/pyworkflow/project.py", line 360, in create
    self.mapper = self.createMapper(self.dbPath)
  File "/ws/local/progs/scipion/pyworkflow/project.py", line 203, in createMapper
    return SqliteMapper(sqliteFn, classesDict)
  File "/ws/local/progs/scipion/pyworkflow/mapper/sqlite.py", line 47, in __init__
    raise Exception('Error creating SqliteMapper, dbName: %s\n error: %s' % (dbName, ex))
Exception: Error creating SqliteMapper, dbName: project.sqlite
 error: unable to open database file

**Comment by pconesa** [comment] 2018-01-30 20:53
We usually do SSH to the server and work there. Also mount "movies" folder
but actually never tried mounting a scipion folder over the network

**Comment by pconesa** [comment] 2020-01-14 13:24
I'm closing this issue. Feel free to reopen it if I'm wrong or missed something.

**Closed by pconesa** 2020-01-14 13:24 UTC
