### ISSUE TITLE
Invert contrast option is failing for Preprocess-Micrographs

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#269] opened 2016-01-25 18:22 UTC
It seems that for big micrographs (~9K pixel size) the xmipp_image_operate --mult -1 is crashing.

The error can be reproduced by starting the tutorial intro:
scipion tutorial intro
Executing the import of micrographs and then in the preprocess-micrograph activate the 'Invert contrast' option.

This issue was dicovered by @pconesa when doing the tutorial and before going to Eman boxer.

**Comment by delarosatrevin** [comment] 2016-01-26 16:58
The problem is about the amount of memory when running 3 mpi processes at the same time. 
Maybe we should review the --mult -1 option, but not for the v1.0.0

**Comment by cossorzano** [comment] 2016-01-26 18:00
It is certainly a memory problem. The problem is not with --mult -1 but with all operations, the solution would be to check the size of the image and leave it mapped on disk if it is larger than a given value. Anyway, it is a not so much an error as a limitation of working with big images in small computers.

**Comment by delarosatrevin** [comment] 2016-01-27 08:05
@cossorzano , should we close this issue? Or leave it open as a remainder to check that limitation?

**Comment by cossorzano** [comment] 2016-01-27 17:24
I would close it

**Closed** 2016-01-27 17:25 UTC
Labels: bug, protocol, xmipp
