### ISSUE TITLE
GemPicker stops without picking

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#868] opened 2017-02-27 13:22 UTC
Using the CPU version

**Comment by azazellochg** [comment] 2017-03-05 19:07
Hi @cossorzano , I have tried cpu version in devel branch, it picks particles. How can I reproduce this?

**Comment by cossorzano** [comment] 2017-03-06 10:31
Thank you, Grigory. Let me prepare a simple example that we can share.

Kind regards, Carlos Oscar

**Comment by ldelcano** [comment] 2017-03-15 12:23
Hi Carlos, I have run the GemPicker test on my laptop and it works fine, however on a fresh Ubuntu 14 machine with Scipion (release_1.1) it gives me the following error. Is that what you are getting?

RUNNING PROTOCOL -----------------
          PID: 18835
      Scipion:  release-1.1 (2017-03-10) a955d6d
   currentDir: /home/cloudadm/ScipionUserData/projects/TestGempickerAutomaticPicking
   workingDir: Runs/000203_ProtGemPicker
      runMode: Restart
          MPI: 1
      threads: 1
 Starting at step: 1
 Running steps 
STARTED: convertInputStep, step 1
  2017-03-15 13:14:04.208530
Input File: Runs/000134_ProtImportAverages/extra/template_sideview.mrc
** Running command: xmipp_transform_mask -i Runs/000134_ProtImportAverages/extra/template_sideview.mrc --create_mask  Runs/000203_ProtGemPicker/extra/maskSch/ref01.tif --mask circular -60                                                                                                                                                                             
FINISHED: convertInputStep, step 1
  2017-03-15 13:14:04.234236
STARTED: runGempickerStep, step 2
  2017-03-15 13:14:04.246493
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid

------------------------------------------------------------------------
                Automatic Particle Picking by gEMpicker                   
------------------------------------------------------------------------

Aborted
** Running command: /home/cloudadm/scipion/software/em/gEMpicker-1.1/gEMpicker_nocuda_Ubuntu_14.04.x64  --nGPU=0 --nCPU=1 --dirRes=Runs/000203_ProtGemPicker/extra/ --angle2D=5 --contrast=0 --thresh=0.200 --threshHigh=0.900 --nPickMax=0 --boxSize=100 --boxDist=10 --boxBorder=0 --dirTgt=Runs/000203_ProtGemPicker/extra --dirSch=Runs/000203_ProtGemPicker/extra/templates --dirMskSch=Runs/000203_ProtGemPicker/extra/maskSch  --mode=0
Traceback (most recent call last):
  File "/home/cloudadm/scipion/pyworkflow/protocol/protocol.py", line 184, in run
    self._run()
  File "/home/cloudadm/scipion/pyworkflow/protocol/protocol.py", line 230, in _run
    resultFiles = self._runFunc()
  File "/home/cloudadm/scipion/pyworkflow/protocol/protocol.py", line 226, in _runFunc
    return self._func(*self._args)
  File "/home/cloudadm/scipion/pyworkflow/em/packages/igbmc/protocol_gempicker.py", line 153, in runGempickerStep
    runGempicker(micName, self._getExtraPath(), self.useGPU.get(), args)
  File "/home/cloudadm/scipion/pyworkflow/em/packages/igbmc/convert.py", line 91, in runGempicker
    pwutils.runJob(None, getProgram(useGPU), args + ' --mode=%d' % mode)
  File "/home/cloudadm/scipion/pyworkflow/utils/process.py", line 51, in runJob
    return runCommand(command, env, cwd)
  File "/home/cloudadm/scipion/pyworkflow/utils/process.py", line 65, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
  File "/home/cloudadm/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/home/cloudadm/scipion/software/em/gEMpicker-1.1/gEMpicker_nocuda_Ubuntu_14.04.x64  --nGPU=0 --nCPU=1 --dirRes=Runs/000203_ProtGemPicker/extra/ --angle2D=5 --contrast=0 --thresh=0.200 --threshHigh=0.900 --nPickMax=0 --boxSize=100 --boxDist=10 --boxBorder=0 --dirTgt=Runs/000203_ProtGemPicker/extra --dirSch=Runs/000203_ProtGemPicker/extra/templates --dirMskSch=Runs/000203_ProtGemPicker/extra/maskSch  --mode=0' returned non-zero exit status 134
Protocol failed: Command '/home/cloudadm/scipion/software/em/gEMpicker-1.1/gEMpicker_nocuda_Ubuntu_14.04.x64  --nGPU=0 --nCPU=1 --dirRes=Runs/000203_ProtGemPicker/extra/ --angle2D=5 --contrast=0 --thresh=0.200 --threshHigh=0.900 --nPickMax=0 --boxSize=100 --boxDist=10 --boxBorder=0 --dirTgt=Runs/000203_ProtGemPicker/extra --dirSch=Runs/000203_ProtGemPicker/extra/templates --dirMskSch=Runs/000203_ProtGemPicker/extra/maskSch  --mode=0' returned non-zero exit status 134
FAILED: runGempickerStep, step 2
  2017-03-15 13:14:04.262092
------------------- PROTOCOL FAILED (DONE 2/4)

**Comment by cossorzano** [comment] 2017-03-16 07:39
I'm not sure about the message because I don't have a project now with 
this error

**Comment by azazellochg** [comment] 2017-03-23 10:25
@ldelcano for the Ubuntu error you could try `export LC_ALL="en_US.UTF-8" `, might fix it.

**Comment by pconesa** [comment] 2017-04-18 07:11
What's the status of this?

**Comment by azazellochg** [comment] 2017-04-18 13:44
I must say there is a bug in gempicker version distributed with scipion - sometimes it crashes at picking particles step due to threshold error. This was fixed long time ago but I didn't find time to recompile the binaries from scratch.

**Comment by pconesa** [comment] 2017-04-19 15:44
Thanks @azazellochg , we might have time to compile, if it's just that the new version....I can see only the binaries at http://gem.loria.fr/gEMpicker/index.php. Can we use those binaries?

**Comment by azazellochg** [comment] 2017-04-19 15:55
@pconesa no, those ones are really outdated. The latest source code for gEM* tools is [here](https://github.com/hvthaibk/ccrunch).

**Comment by pconesa** [comment] 2017-04-19 16:52
Thanks! Will have a look.

**Comment by cossorzano** [comment] 2017-04-20 12:53
My update on this is that it is already working although it stops with an error
00287:   ------------------------------------------------------------------------
00288:                   Automatic Particle Picking by gEMpicker                   
00289:   ------------------------------------------------------------------------
00290:   
00291:   Micrograph: Runs/007592_ProtGemPicker/extra/
00292:   Reference:  Runs/007592_ProtGemPicker/extra/templates/
00293:   Mask:       Runs/007592_ProtGemPicker/extra/maskSch/
00294:   Result:     Runs/007592_ProtGemPicker/extra/
00295:   
00296:   Running /home/coss/scipion/software/em/gEMpicker_v1.1/gEMpicker_nocuda_Ubuntu_14.04.x64: use 
00297:                  number of micrographs              = 1
00298:                  number of references               = 15
00299:                  number of mask images              = 1 (identical mask)
00300:                  running mode                       = 0 (correlation)
00301:                  in-plane rotating angle (degree)   = 5
00302:                  micrograph contrast                = 1 (positive peaks)
00303:                  peak threshold value (low)         = 0.1
00304:                  peak threshold value (high)        = 0.5
00305:                  max number of picked particles     = 0 (no limit)
00306:                  size of picked particles           = 0 (use reference size)
00307:                  min distance between peaks         = 0 (use reference size)
00308:                  min distance box-micrograph        = 0
00309:                  number of processes (MPI)          = 1
00310:                  number of GPUs      / process      = 0
00311:                  number of CPU cores / process      = 12
00312:                  distribution of micrographs (MPI)  = No
00313:                  
00314:   Params processing time: 0.040688
00315:   
00316:   Computing correlation maps...
00317:   
00318:   Processing micrograph 1/1: Runs/007592_ProtGemPicker/extra/050_movie_aligned_mic.mrc
00321:        100%     Correlation time:    1 nProc,     0 nGPU,    12 nCPU,    161.910822
00322:   
00323:   Total correlation time: 161.911
00324:   Total computation time: 165.968
00325:   
00326:   gEMpicker runs successfully!!!
00327:   
00328:   
00329:   ------------------------------------------------------------------------
00330:                   Automatic Particle Picking by gEMpicker                   
00331:   ------------------------------------------------------------------------
00332:   
00333:   Micrograph: Runs/007592_ProtGemPicker/extra/
00334:   Reference:  Runs/007592_ProtGemPicker/extra/templates/
00335:   Mask:       Runs/007592_ProtGemPicker/extra/maskSch/
00336:   Result:     Runs/007592_ProtGemPicker/extra/
00337:   
00338:   Running /home/coss/scipion/software/em/gEMpicker_v1.1/gEMpicker_nocuda_Ubuntu_14.04.x64: use 
00339:                  number of micrographs              = 1
00340:                  number of references               = 15
00341:                  number of mask images              = 1 (identical mask)
00342:                  running mode                       = 1 (picking, box only)
00343:                  in-plane rotating angle (degree)   = 5
00344:                  micrograph contrast                = 1 (positive peaks)
00345:                  peak threshold value (low)         = 0.1
00346:                  peak threshold value (high)        = 0.5
00347:                  max number of picked particles     = 0 (no limit)
00348:                  size of picked particles           = 0 (use reference size)
00349:                  min distance between peaks         = 0 (use reference size)
00350:                  min distance box-micrograph        = 0
00351:                  number of processes (MPI)          = 1
00352:                  number of GPUs      / process      = 0
00353:                  number of CPU cores / process      = 12
00354:                  distribution of micrographs (MPI)  = No
00355:                  
00356:   Params processing time: 0.0368149
00357:   
00358:   Picking particles using correlation maps...
00359:   
00360:   Processing micrograph 1/1: Runs/007592_ProtGemPicker/extra/050_movie_aligned_mic.mrc
00361:   
00362:   Requirement failed: size_t cResultPicker<T>::refineUsingHighThreshold(float thresholdHigh): empty cResultPicker object
00363:   

Maybe it is related to the bug you are fixing with the new compilation

**Comment by azazellochg** [comment] 2017-04-20 12:58
@cossorzano yes, this is exactly this bug. Usually it goes away if one plays with high threshold value.

**Comment by pconesa** [comment] 2017-06-01 11:03
@josuegbl has tried to compile it but it wasn't easy. I'm taking it out of the release.

**Comment by azazellochg** [comment] 2017-10-19 17:42
Hi all, I have got one binary where this bug is supposed to be fixed:
[gEMpicker_cuda_55.tar.gz](https://github.com/I2PC/scipion/files/1399434/gEMpicker_cuda_55.tar.gz)
@cossorzano you might want to check if it works for you.

**Comment by azazellochg** [comment] 2018-04-09 16:09
I guess I will close this since the program is not developed anymore (no new cuda version support) and we probably will deprecate it in release 1.3. Other opinions?

**Closed by azazellochg** 2018-04-09 16:09 UTC
Labels: bug, ready
