### ISSUE TITLE
crash when executing radial average (xmipp calculator 3D)

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#334] opened 2016-02-22 15:59 UTC
1) input mrc volume produced by relion
2) Error

00002:         Scipion: v1.0.0
00003:      currentDir: /mnt/big/carmen/datos5/ScipionUserData/projects/TsV_N1_cryo1
00004:      workingDir: Runs/002726_XmippProtImageOperateVolumes
00005:         runMode: Restart
00006:             MPI: 1
00007:         threads: 2
00008:   Traceback (most recent call last):
00009:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00010:       self._run()
00011:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/protocol.py", line 930, in _run
00012:       self._insertAllSteps() # Define steps for execute later
00013:     File "/usr/local/ScipionStable/scipion/pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_process.py", line 128, in _insertAllSteps
00014:       self._insertProcessStep()
00015:     File "/usr/local/ScipionStable/scipion/pyworkflow/em/packages/xmipp3/protocol_preprocess/protocol_image_operate.py", line 125, in _insertProcessStep
00016:       writeSetOfVolumes(self.inputVolumes2.get(), inputFn2)
00017:     File "/usr/local/ScipionStable/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 586, in writeSetOfVolumes
00018:       writeSetOfImages(volSet, filename, volumeToRow, blockName, **kwargs)
00019:     File "/usr/local/ScipionStable/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 835, in writeSetOfImages
00020:       setOfImagesToMd(imgSet, md, imgToFunc, **kwargs)
00021:     File "/usr/local/ScipionStable/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 802, in setOfImagesToMd
00022:       kwargs['alignType'] = imgSet.getAlignment()
00023:   AttributeError: 'NoneType' object has no attribute 'getAlignment'
00024:   Cleaning temporarly files....

3) educated guess: scipion thinks the input is a 2D set of images and tries to access to the getAligment atribute

4) possible solution: cast file using :mrc

   ;-)

**Comment by delarosatrevin** [comment] 2016-02-22 16:04
Could you kindly add a test for this protocol that reflect tihs bug?
There are existing volumes in the current test data that have volumes produced by Relion.
Without looking at the issue, I also guess that the problem is what @rmarabini  suggests.

**Comment by josuegbl** [comment] 2016-06-06 14:34
Calculator 2D/3D (Now named "operate particles/volume" respectively) protocols are remade because the code was too old and does not work. Now there are some tests to ensure its operation. Regarding the tests, some of them not pass because the xmipp program fails...


command line: scipion test tests.em.protocols.test_protocols_xmipp_3d.TestXmippOperateVolumes
error 1: 
00015:   STARTED: operationStep, step 2
00016:     2016-06-06 16:06:30.545619
00017:   xmipp_image_operate -i Runs/000002_ProtImportVolumes/extra/BPV_scale_filtered_windowed_64.vol  --dot_product  Runs/000037_ProtImportVolumes/extra/volume_1_iter_002.mrc:mrc -o Runs/000187_XmippProtImageOperateVolumes/extra/output_volume.vol 
00018:   XMIPP_ERROR 2:  Incorrect argument received
00019:   Dot product can only be computed between two files
00020:   File: software/em/xmipp/libraries/data/image_operate.cpp line: 441

error 2:
00017:   xmipp_image_operate -i Runs/000154_XmippProtImageOperateVolumes/tmp/input_volumes.xmd  --column  20 -o Runs/000154_XmippProtImageOperateVolumes/extra/output_volumes.stk  --save_metadata_stack Runs/000154_XmippProtImageOperateVolumes/extra/output_volumes.xmd --keep_input_columns
00018:   Input File: Runs/000154_XmippProtImageOperateVolumes/tmp/input_volumes.xmd
00019:   Output File: Runs/000154_XmippProtImageOperateVolumes/extra/output_volumes.stk
00020:   0000/???? sec. ------------------------------------------------------------XMIPP_ERROR 48:  Incorrect MultidimArray size.
00021:   ImageBase::Write: images source and target have different sizes:
00022:   Image source to be written (x,y,z,n) = 64 64 1 1
00023:   Image file target Runs/000154_XmippProtImageOperateVolumes/extra/output_volumes.stk (x,y,z,n) = 64 64 64 2
00024:   File: software/em/xmipp/libraries/data/xmipp_image_base.cpp line: 867

Maybe @rmarabini and/or @cossorzano know the solution (or can find the mistake in the tests and/or the code).

**Comment by cossorzano** [comment] 2016-06-08 06:00
Which is this branch?

**Comment by josuegbl** [comment] 2016-06-09 07:12
v1.0

**Comment by delarosatrevin** [comment] 2016-06-09 13:44
The following test is failing in my laptop.

scipion test tests.em.protocols.test_protocols_xmipp_3d.TestXmippOperateVolume

**Comment by josuegbl** [comment] 2016-06-14 11:03
@delarosatrevin , In branch V1.0 this test (scipion test tests.em.protocols.test_protocols_xmipp_3d.TestXmippOperateVolumes) no fails, at least in my laptop. Check again and close the issue if it no fails.

**Comment by delarosatrevin** [comment] 2016-06-14 13:53
@josuegbl , You are right, this test is passing, I think it fails if you do not have internet connection (that could be my case when reporting this). I think @rmarabini download some file in this test not in the standard way of the testdata, which makes imposible to run the tests offline...but this is a different story.

**Closed by delarosatrevin** 2016-06-14 13:53 UTC
Labels: protocol
