### ISSUE TITLE
Java exception when changing the boxsize in the Picking GUI

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1233] opened 2017-10-02 06:33 UTC
@pconesa I think after you changes in the picking there is an Exception when changing the box size.

java -Xmx2g -d64 -Djava.library.path=/home/josem/work/development/scipion/software/em/xmipp/lib -Dplugins.dir=/home/josem/work/development/scipion/software/em/xmipp/external/imagej/plugins -cp /usr/lib/jvm/java-8-openjdk-amd64/lib/*:/home/josem/work/development/scipion/software/em/xmipp/external/imagej/*:/home/josem/work/development/scipion/software/em/xmipp/java/lib/* xmipp.viewer.particlepicker.training.SupervisedPickerRunner --input ./Tmp/8746.outputMicrographsDoseWeighted_micrographs.xmd --output ./Tmp/8854.outputCoordinates --scipion 60553 --tmp true
Oct 02, 2017 8:31:33 AM xmipp.viewer.particlepicker.training.model.ManualParticle loadImagePlus
SEVERE: null
java.lang.ArrayIndexOutOfBoundsException: 9768960
        at ij.process.FloatProcessor.crop(FloatProcessor.java:727)
        at xmipp.viewer.particlepicker.training.model.ManualParticle.loadImagePlus(ManualParticle.java:81)
        at xmipp.viewer.particlepicker.training.model.ManualParticle.getImageGeneric(ManualParticle.java:114)
        at xmipp.viewer.particlepicker.training.model.SupervisedParticlePicker$UpdateTemplatesTask.doInBackground(SupervisedParticlePicker.java:1298)
        at xmipp.viewer.particlepicker.training.model.SupervisedParticlePicker$UpdateTemplatesTask.doInBackground(SupervisedParticlePicker.java:1249)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

java.lang.IllegalArgumentException: 9768960
        at xmipp.viewer.particlepicker.training.model.ManualParticle.loadImagePlus(ManualParticle.java:87)
        at xmipp.viewer.particlepicker.training.model.ManualParticle.getImageGeneric(ManualParticle.java:114)
        at xmipp.viewer.particlepicker.training.model.SupervisedParticlePicker$UpdateTemplatesTask.doInBackground(SupervisedParticlePicker.java:1298)
        at xmipp.viewer.particlepicker.training.model.SupervisedParticlePicker$UpdateTemplatesTask.doInBackground(SupervisedParticlePicker.java:1249)
        at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at javax.swing.SwingWorker.run(SwingWorker.java:334)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by pconesa** [comment] 2017-10-02 09:45
Always?, Did you have an ongoing training? Nevertheless I'll have a look. Thanks.

**Comment by pconesa** [comment] 2017-10-02 09:53
Not able to reproduce it...any specific sequence. I guess you where picking in tmp....after analyze result?

**Comment by pconesa** [comment] 2017-10-13 06:44
@delarosatrevin , have you seen this again?

**Comment by pconesa** [comment] 2017-10-31 13:50
@delarosatrevin , anyway I can reproduce this?

**Comment by pconesa** [comment] 2019-09-10 10:00
I'm closing this issue. I've made some changes and never got this exception. Feel free to reopen it.

**Closed by pconesa** 2019-09-10 10:00 UTC
Labels: bug, gui, java
