### ISSUE TITLE
frealign classify fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1002] opened 2017-05-12 16:30 UTC
I'm getting this with default values. I' might be doing thing wrong since is the first time I use it but I guess this error should not hapend:
00015:   STARTED: constructParamFilesStep, step 2
00016:     2017-05-12 18:27:40.932767
00017:   Traceback (most recent call last):
00018:     File "/home/local/scipion/pyworkflow/protocol/executor.py", line 137, in run
00019:       self.step._run()  # not self.step.run() , to avoid race conditions
00020:     File "/home/local/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00021:       resultFiles = self._runFunc()
00022:     File "/home/local/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00023:       return self._func(*self._args)
00024:     File "/home/local/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 600, in constructParamFilesStep
00025:       film = micIdMap[img.getMicId()]
00026:   KeyError: 1
00027:   Protocol failed: 1
00028:   FAILED: constructParamFilesStep, step 2

**Comment by delarosatrevin** [comment] 2017-05-16 11:29
Someone here was trying to do a classification with frealign and the first computing steps were running for 4 days and my guess is that it was stuck. @josuegbl, any comment about this? Is there any trick using the protocol or maybe a bug in the conversion of the required input files?

**Comment by yaizar** [comment] 2017-05-31 15:03
We figured out the issue came because the particles were extracted with relion, and the micId was lost (it has to be accessed through the coordinate). We have added a fix so that it can handle taking micIds from the coordinate, but @josuegbl will look into making relion's extract particles keep  the micIds in the particles themselves. 

When I was trying to reproduce this using particles from relion 3d auto-refine and the option "use initial angles/shifts" set to Yes, I got a different error: 
![image](https://cloud.githubusercontent.com/assets/4609687/26638668/f415a73e-4622-11e7-906c-ce874b1f032e.png)

**Comment by delarosatrevin** [comment] 2017-05-31 15:06
I think the issue of missing micId is fixed in one of the relion-fixes
branch, but maybe not merged into release-1.1. @josuegbl, can you check
this?

**Comment by josuegbl** [comment] 2017-05-31 19:57
You are right @delarosatrevin, this issue is in release-1.1-fixes-relion2 branch and it is not merged yet. Im going to merge the branches as soon as possible.

**Closed** 2017-06-08 10:37 UTC
Labels: to-review
