### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by kylelmorris** [I2PC/scipion#604] opened 2016-10-12 17:50 UTC
I'm new to Scipion (using v 1.0.1) so please forgive me if this would be obvious to an experienced user or hiding somewhere in documentation. 

When running RANSAC on a set of 20 averages (80 px^2) from xmipp cl2d I get the following error at 610/618:

'maximum recursion depth exceeded while calling a Python object'

I noted issue #547 and tried copying the protocol and running in continue mode but get a similar error straight away:

'maximum recursion depth exceeded in __subclasscheck__'

I've attached the workflow.json and run.stdout. If it's possible to fix this please let me know! Thanks for your help.

[workflow_and_run.zip](https://github.com/I2PC/scipion/files/525255/workflow_and_run.zip)

**Comment by delarosatrevin** [comment] 2016-10-12 18:04
Dear @kylelmorris , 
No need to forgive, all kind of feedback is important for us, even from users that are new to Scipion. There are some reported mistakes that help us to make things more intuitive or improve the documentation. 

I opened the attached zip file, but in the run.stdout I didn't found the 'maximum recursion...' error. Did you attached the problematic one? The last thing I saw there is 'PROTOCOL FINISHED'. 

I would be great to see the full log of the error to figuring out what is happening. 
Thanks for you feedback.

**Comment by kylelmorris** [comment] 2016-10-12 18:15
Thanks for your speedy response!

Attached are all the logs associated with the problematic protocol 002378. I couldn't find the error by grep on the log files but attach a screenshot showing how this is reported in the GUI. Further I note that it has actually made 9 volumes.

[logs.zip](https://github.com/I2PC/scipion/files/525314/logs.zip)

**Comment by delarosatrevin** [comment] 2016-10-12 19:42
Hum...it is very weird because in the run.db and the steps.sqlite everything seems like the protocol have properly finished. Are you sure it only generated 9 volumes? The counting in this protocol starts at 0, so it should be a volume000.vol in the extra folder. 

Could you activate the flag SCIPION_DEBUG before launching the GUI? This should print more information about the error. In bash should be like this:
export SCIPION_DEBUG=1

**Comment by kylelmorris** [comment] 2016-10-13 00:30
Excuse me, starting at 000 it got to 009 so 10 volumes. OK, so it did finish. Somehow then just the GUI is broken and I cannot analyse or pass on the results inside Scipion because it thinks it failed. I am running again in DEBUG mode and will report back.

Thanks for your help!

**Comment by kylelmorris** [comment] 2016-10-13 18:52
Totally puzzled by not being able to reproduce this, but pleased, RANSAC ran fine this time. 

In the same project, I'm tackling a different issue that the RCT reconstruction consistently fails, may I comment on this here or start a new thread? Thanks again for your help.

**Comment by delarosatrevin** [comment] 2016-10-13 19:28
It is good that Ransac is now working, but also annoying that can not be
reproduced. Then, I would recommend to close this issue and reopen it later
if we can reproduce it. What do you think?

About the RCT issue, it would better to open a new one. Could you attach
the log files?

**Comment by kylelmorris** [comment] 2016-10-13 19:39
Got it :) thanks, will update on new issue.

**Closed** 2016-10-13 19:38 UTC
