### ISSUE TITLE
Scipion does not compile

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#1567] opened 2018-04-17 21:16 UTC
After updating I get this error when compiling:

scons: Reading SConscript files ...
Mkdir("/home/jvargas/scipion/software/em/xmipp/java/build")
scons: done reading SConscript files.
scons: Building targets ...
scons: `software/lib/libXmippAlglib.so' is up to date.
scons: `software/lib/libXmippBilib.so' is up to date.
scons: `software/lib/libXmippCondor.so' is up to date.
scons: `software/lib/libXmippDelaunay.so' is up to date.
gcc -o software/em/xmipp/external/sqliteExt/extension-functions.os -c -fPIC -Isoftware/em/xmipp/external -Isoftware/em/xmipp/libraries -Isoftware/include software/em/xmipp/external/sqliteExt/extension-functions.c
software/em/xmipp/external/sqliteExt/extension-functions.c:124:24: fatal error: sqlite3ext.h: No such file or directory
compilation terminated.
scons: *** [software/em/xmipp/external/sqliteExt/extension-functions.os] Error 1
scons: building terminated because of errors.

**Comment by pconesa** [comment] 2018-04-23 09:36
Can we close this?

**Comment by josuegbl** [comment] 2018-04-25 15:00
I think the problem is still here... I mean, the installation fails every time you go and/or go back to/from devel-related branches. I know a temporary solution is to execute the script clean.py (**./scipion python scripts/clean.py all**), but for most of scipion developers is not clear.

**Comment by pconesa** [comment] 2019-08-09 11:37
This should be gone now.

**Closed by pconesa** 2019-08-09 11:37 UTC
Labels: bug
