### ISSUE TITLE
Scipion relion - particles extraction

### ISSUE THREAD

**Issue by S160024** [I2PC/scipion#2041] opened 2019-08-23 03:31 UTC
Usually when running in Relion 3.0, the particles extracted would result in an output file that can be read for 2D classifications. However, in Scipion, there seems to be an error in producing the output file. 

Step 2 in Scipion-relion particles extraction failure.  The particles extractions was performed properly, however, the output file is not available. 

![Capture](https://user-images.githubusercontent.com/54427056/63564832-3a485d80-c599-11e9-8765-e9ba2172c5a3.JPG)

Despite editing the failed process and clicking continue, the error still pops up. Is there a bug issue or is there a coding issue? I'm currently running on Ubuntu Centos 7.

**Comment by pconesa** [comment] 2019-08-23 08:19
Thank you @S160024 , I'm involving here Relion plugin developers

**Comment by azazellochg** [comment] 2019-08-23 13:28
@S160024 could you provide full output logs, screenshot of protocol parameters used so we could reproduce it? Also, are you running extraction in streaming or not?

**Comment by delarosatrevin** [comment] 2019-08-23 13:49
From the shown error trace, it seems to be in streaming...still will be good to have full logs and parameters.

**Comment by azazellochg** [comment] 2019-09-01 14:20
@S160024 any update on this?

**Comment by S160024** [comment] 2019-09-03 06:59
Hi there sorry for the late response.

The full log file is attached. 
[run.log](https://github.com/I2PC/scipion/files/3568149/run.log)

The parameters used is the coordinates from relion's autopicking LoG output file The micrograph source are from xmipp3-ctf consensus output file. The particle box size is 150 px, with no rescale of particles. 

The preprocess parameters are as follows:
1. no invert contrast
2. no normalise particles. 

the streaming was set as 0 seconds sleep when waiting and 0 batch size.

**Comment by azazellochg** [comment] 2019-09-03 09:11
Thanks, @S160024, we'll try to reproduce it. Could you also attach run.stdout which is more detailed?

**Comment by S160024** [comment] 2019-09-03 15:17
Hi @azazellochg , I'm unable to attach it. However, i've uploaded on dropbox and you may access the run.stdout file in the link below.

https://www.dropbox.com/s/j1oiwlhdktp5i80/run.stdout?dl=0

**Comment by JuhaHuiskonen** [comment] 2019-10-12 17:38
For me 'relion - particle extraction' is also failing when I try to extract using coordinates from 'relion - auto-picking LoG' in streaming mode

**Comment by azazellochg** [comment] 2020-01-05 22:07
Confirmed as a bug in core extraction protocol

**Comment by pconesa** [comment] 2020-01-07 06:30
Thanks @azazellochg , have you manage to reproduce it. Since test are passing, I guess there must be a specific condition that makes it fail and test are not covering? I guess we can assign it to us.

**Comment by azazellochg** [comment] 2020-01-07 09:34
I was able to reproduce it in cistem since I copied the relion code from that protocol to cistem picker.

**Comment by azazellochg** [comment] 2020-11-09 19:21
This is definitely fixed.

**Closed by azazellochg** 2020-11-09 19:21 UTC
Labels: bug
