### ISSUE TITLE
createEmptyFileStep

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#421] opened 2016-05-09 22:08 UTC
createEmptyFileStep in python is defined as

PyObject *
xmipp_createEmptyFile(PyObject *obj, PyObject *args, PyObject *kwargs)
{
    int Xdim,Ydim,Zdim;
    size_t Ndim;
    Zdim=1;
    Ndim=1;
    PyObject * input;
    if (PyArg_ParseTuple(args, "Oii|ii", &input, &Xdim, &Ydim, &Zdim,
                         &Ndim))
    {
       createEmptyFile(PyString_AsString(input),Xdim,Ydim,Zdim,Ndim,true,WRITE_REPLACE);
        Py_RETURN_NONE;
    }
    return NULL;
}

Unfortunatelly the C function is defined as

void createEmptyFile(const FileName &_filename, int Xdim, int Ydim, int Zdim = 1,
                     size_t select_img = APPEND_IMAGE, bool isStack = false,
                     int mode = WRITE_OVERWRITE, int _swapWrite = 0);

that is Ndim in python is used as select_img. This cannot be good :-(

**Comment by delarosatrevin** [comment] 2016-06-06 09:42
I think this is working....the problem is in the Xmipp function definition...where it use select_img when it is really N. 
I have added a test for the function in f8747fc.
I will close this issue and only reopen if a related bug is found.

**Closed** 2016-06-06 09:42 UTC
