### ISSUE TITLE
Integrate new version of motioncor2 

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#908] opened 2017-03-16 10:01 UTC
We should consider to integrate the new version of motioncor2, it was announced in Feb/2017 in the ccpem mailing list:

The new version of MotionCor2 has been released on our website
http://msg.ucsf.edu/em/software/index.html
This version has implemented the following new functions in addition to bug fixing.
1. Correction of anisotropic magnification. This correction is integrated with the correction of local motion. There is no extra real-space interpolation as a result.
2. Archiving input movie stacks of 8 bits per pixel into MRC files with 4 bits per pixel.
3. Allow stacks to be aligned to user specified frames. 
This version is compiled with CUDA 8. For your convenience, the last version of MotionCor2 is still kept on our website.

It was also requested by @JuhaHuiskonen and some uses at Stockholm

**Comment by azazellochg** [comment] 2017-03-16 10:13
duplicate of #797
I will try to do it this week-end.

**Closed** 2017-03-16 10:16 UTC
Labels: feature, protocol, wishlist
